### PR TITLE
Bugfix: wrong encoder for CP-437

### PR DESCRIPTION
**Pull request by muyinliu**
Can be verify with following lisp code:

```lisp
(every #'identity
       (loop
         for i from 0 below 255
         collect (equal 
                  i
                  (elt
                   (babel:string-to-octets
                    (babel:octets-to-string (make-array 1 
                                                        :element-type '(unsigned-byte 8)
                                                        :initial-element i)
                                            :encoding :cp437)
                    :encoding :cp437)
                   0))))
```
=>
```=>
T
```

### CODE REVIEW

**Comment by muyinliu** [comment]
@luismbo Please take some time to review this PR. Thanks.

**Comment by luismbo** [comment]
Could you add a test similar to `iso-8859-decode-check` based on the flexi-streams tables? If you don't have time, that's ok, I can merge this as is. Thanks.

**Comment by muyinliu** [comment]
> Could you add a test similar to `iso-8859-decode-check` based on the flexi-streams tables? If you don't have time, that's ok, I can merge this as is. Thanks.

Wait a second.

**Comment by muyinliu** [comment]
> Could you add a test similar to `iso-8859-decode-check` based on the flexi-streams tables? If you don't have time, that's ok, I can merge this as is. Thanks.

Done. 

```shell
sbcl --noinform --eval "(asdf:test-system 'babel)" --quit
```
=>
```=>
WARNING:
   Deprecated recursive use of (ASDF/OPERATE:OPERATE 'ASDF/LISP-ACTION:LOAD-OP
   '("babel-tests")) while visiting (ASDF/LISP-ACTION:TEST-OP "babel") - please
   use proper dependencies instead
WARNING:
   Deprecated recursive use of (ASDF/OPERATE:OPERATE 'ASDF/LISP-ACTION:TEST-OP
   '("babel-tests")) while visiting (ASDF/LISP-ACTION:TEST-OP "babel") - please
   use proper dependencies instead
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
..................

#<test-run: 59 tests, 498 assertions, 0 failures in 0.049793 sec>

[no failures!]
```

**Comment by luismbo** [comment]
@muyinliu many thanks!

**Pull request merged**
