### PR TITLE
get-character-encoding by string.

### PR DESCRIPTION
**Pull request by pocket7878**
Sometimes want to lookup character encoding by string. (e.g HTTP body parsing)
So handling string inside get-character-encoding.

### CODE REVIEW

**Comment by pocket7878** [comment]
It seems source-forge was down while running build.
So please re-run travis ci build, or should I close & reopen this PR to reflesh build status?

**Comment by sionescu** [comment]
I'm against using strings, also because interning like this leaves open the possibility of DOS attacks if the caller doesn't validate the string, in which case it might as well do the interning before calling into Babel.

**Comment by luismbo** [comment]
Looking up encodings by string sounds useful. @sionescu has a point there. Let's avoid using INTERN.

**Comment by sionescu** [comment]
We can add a slot to class character-encoding, named e.g. "aliases", and then notice-character-encoding would build a hash-table, and check that they are unique, etc...

**Comment by luismbo** [comment]
Yeah, that sounds like a good idea. I remember wanting to avoid aliases since there are so many of them, but it's probably useful to have them.

**Comment by sionescu** [comment]
We can start with the official list: https://www.iana.org/assignments/character-sets/character-sets.xhtml

**Comment by pocket7878** [comment]
Thank you for your comments! 
So, character-encoding class already have aliases, we must check aliases by official list.
And, I think it is better to create a function that take a string and check if the string is a correct encoding name that babel supports (of course without INTERN).
So I think we should also collect encoding-names(include alias names) into one list(or perhaps a Set?) search name by string.

**Comment by luismbo** [comment]
@pocket7878 Heh, I didn't remember there was an `aliases` slot already. That's nice. :) OK, so I think `*character-encodings*` should map case-insensitive strings (rather than keywords) to encodings.

I think it would be nice to grab the aliases from https://www.iana.org/assignments/character-sets/character-sets.xhtml automatically rather than copying and pasting to each `define-character-encoding` form. Perhaps `notice-character-encoding` can open the csv (or whichever format is most convenient) and fill in the aliases?

Do you have all the information you need to update the pull request with this implementation strategy? (Assuming you agree with it, of course. :))

**Comment by pocket7878** [comment]
@luismbo 
Thank you for you comment!
Yes I'm agree with it. But which is a better way to grab aliases from official list?
- whenever invoke notice-character-encoding open csv file and lookup alias names.
- Reading csv file once and caching data on some special-variable and use it in notice-character-encoding.

**Comment by pocket7878** [comment]
I just updated PR to use offical csv file. 
And I selected first way, so every time notice-character-encoding called csv file read.

**Comment by pocket7878** [comment]
@luismbo 
It looks like loading cl-csv is failed by heap size limit of alisp. 
Is there any light-weight and reliable csv read library? Or should I read csv by myself?

**Comment by luismbo** [comment]
@pocket7878 I've had good luck with `fare-csv`. Don't forget to use the stream API, rather than read the whole file into memory.

**Comment by sionescu** [comment]
How about we just mark Allegro as allowed failure ? The heap limit is just annoying.

**Comment by luismbo** [comment]
@sionescu true, but in this case, it might have helped us notice an inefficiency. Normally I wouldn't worry too much about it, but babel is already a bit slow to compile.

**Comment by pocket7878** [comment]
@luismbo , @sionescu  Thank you for your comments!
I just update to use fare-csv instead of cl-csv, and passed tests :smile:

**Comment by luismbo** [comment]
I wonder if we should pre-process the csv and generate a lisp file instead of doing it at compile-time and adding dependencies on fare-csv and split-sequence just because of that. Maybe I'm being overly conservative?

**Comment by sionescu** [comment]
I agree with the approach. I've also thought of doing that in IOlib
given that the system libc ABI is guaranteed to be stable.

> I wonder if we should pre-process the csv and generate a lisp file
> instead of doing it at compile-time and adding dependencies on fare-
> csv and split-sequence just because of that. Maybe I'm being overly
> conservative?


> — Reply to this email directly or view it on GitHub[1].


>


--
Stelian Ionescu a.k.a. fe[nl]ix
Quidquid latine dictum sit, altum videtur.
http://common-lisp.net/project/iolib
 


Links:

  1. https://github.com/cl-babel/babel/pull/25#issuecomment-127259018

**Comment by pocket7878** [comment]
@luismbo , @sionescu Thank you for your comments.
I just updated my PR to create lisp file from official-csv and use it.

**Comment by luismbo** [comment]
@pocket7878 awesome. Please include the program you used to generate the lisp file.

**Comment by pocket7878** [comment]
@luismbo Thanks. I wrote my generate program in ruby (working in 2.2.2).

**Comment by luismbo** [comment]
Oh, no! Blasphemy! ;-)

**Comment by pocket7878** [comment]
So I rewrite my script in lisp.

**Comment by pocket7878** [comment]
@luismbo Why not merge in?

**Comment by luismbo** [comment]
@pocket7878 because I suck! Sorry, I'll get to it ASAP this week!

**Pull request closed without merging**
