### PR TITLE
Korean CP949 encodings.

### PR DESCRIPTION
**Pull request by ageldama**
Hi,

Would you like to pull & merge this Korean encodings for cl-babel?
- CP949 aka "UHC", or "Extended EUC-KR". Widely, mostly used in South Korea. (before UTF-8)

Thanks.

**EDIT** : Removed JOHAB encoding in this time.

### CODE REVIEW

**Comment by ageldama** [comment]
Dear @luismbo ,

It was been long time since last commit, sorry.

I rewrote Korean CP949 encoder/decoder, 
also I added proper error handlings with `encoding-error` and `decoding-error` conditions.

It seems this is related with #29 . (in prior `tests.lisp` 's `(deftest cp949)`)
For example, `cp949.sexp` tries to DECODE octet `#(#\c9 #\a1)`, but they cannot be mapped from CP949.

(Yes, I know, I have already mentioned this things.)
Please see this link: 
  http://unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP949.TXT 
..They may seems proper, but they aren't in mappings, thus they cannot be mapped.)

It would be same with another encodings, I guess. (EUC-JP, GBK...)

Anyway, I think you need to revise this testcase, to become *green*.


Thanks.

**Comment by luismbo** [comment]
Hello @ageldama. Welcome back. :-) Which test case needs to be reviewed? Travis CI says all tests have passed. Is it some other test that hasn't been committed yet?

**Comment by ageldama** [comment]
Thank you.

The "cp949" test, I mean. 
Yes, it passes, but I think it's strange.

Please see these;
(babel-tests:run) with master

(babel-tests:run) with kor-cp949

I guess, as I mentioned earlier, "trying to encode/decode unmappable octets/codepoint" -causes this.
And I don't know how to /inspect/ this errors. (Sorry, could you give me any tips? I use SLIME)

I think it would be important your opinion on this.


Thank you.

**Comment by ageldama** [comment]
Well, this is strange.

https://travis-ci.org/cl-babel/babel/jobs/156234753

On my desktop:
default

**Comment by ageldama** [comment]
Dear @luismbo ,

It would be ok to merge, but it would not pass prior `tests/cp949.sexp` test, because these contains unmappable characters in CP949 encoding. Of course, I have added some codes to raise decoder-errors. So, I have told you that you should review this 'cp949' test before. That's why.

I hope you merge this PR soon. 👍 

Thanks.

**Comment by ageldama** [comment]
Dear @luismbo ,

It seems my mistake, I had almost forgot that merge from master to my branch, so it was broken on testing, sorry.

Anyway, I revised CP949 test case to pass even with unmappable octets in CP949. (Of course, there are test for *sane-mappings*)

Thanks!

**Comment by ageldama** [comment]
@luismbo Can you please merge this?

**Pull request closed without merging**
